### ISSUE TITLE
error - cutting into non-free mapping when booting 32bit Windows on i386 real hardware

### ISSUE THREAD

**Issue by prontoguy** [maharmstone/quibble#106]
I got another problem, very similar to #75. This time happens on 32bit efi real hardware. Again, it fails at mem.cpp:316.
Both mapping1 and mapping2 have the same memory type (LoaderFirmwareTemporary). 

mapping 1 start at 0x7ca86000 and end at 0x7ca95fff
mapping 2 start at 0x7c985000 and end at 0x7cbf5fff

**Comment by maharmstone** [comment]
What's your motherboard?

**Comment by prontoguy** [comment]
This is asus t100 transformer netbook
