### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [maharmstone/quibble#11]
I would like to point out that an identifier like “[`_EFI_QUIBBLE_PROTOCOL`](https://github.com/maharmstone/quibble/blob/364c07f6b115adf1ae42fb9d8914fb35e4286a2e/src/quibbleproto.h#L36 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by maharmstone** [comment]
This is mimicking what gnu-efi does. Get them to change their practice and I'll follow suit.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by maharmstone** [comment]
Well, I'm sure it'll keep me awake at night. Thanks anyway.
