### ISSUE TITLE
Questions about performance and conversion time

### ISSUE THREAD

**Issue by jinchlu** [maharmstone/quibble#112]
I have a 16TB ntfs disk, how long time does it take to convert to btrfs? The disk is full of data.
Thank you very much, looking forward to your reply.

**Comment by maharmstone** [comment]
I'm guessing you meant to post this on the ntfs2btrfs repo.

The limiting factor is the checksumming process, which involves reading everything on the disk, so for 16TB at 100MB/s this implies upwards of 48 hours.
