### ISSUE TITLE
ReactOS code usage worth mentioning it 

### ISSUE THREAD

**Issue by jeditobe** [maharmstone/quibble#14]
Could you please mention in the Licence part of Readme, that you used some parts of ReactOS Freeloader code?

**Comment by maharmstone** [comment]
I didn't use any Freeloader code. I copied some constant names, that was all.

**Comment by jeditobe** [comment]
okay, I see now...

**Comment by maharmstone** [comment]
I've removed the comments that referenced ReactOS - I agree that they were misleading. There's no need for them when the information ultimately comes from publicly available header files.
