### ISSUE TITLE
Windows 7 x64

### ISSUE THREAD

**Issue by MegaZeroX10** [maharmstone/quibble#16]
How do I go about installing it in that OS?

**Comment by binarymaster** [comment]
Just read the readme?

**Comment by MegaZeroX10** [comment]
Its not possible to do it yet since it doesn't support real machines. It just supports Qemu VMs. I am closing this issue and will keep an eye on its source to see when it supports more than just VMs.

**Comment by maharmstone** [comment]
No, it doesn't _necessarily_ support real machines. It didn't work on mine, but it might well work on yours.
