### ISSUE TITLE
Support of Classic BIOS

### ISSUE THREAD

**Issue by theuserbl** [maharmstone/quibble#17]
Please add support for classic BIOS.

**Comment by maharmstone** [comment]
Not going to happen - this is _way_ out of the scope of the project. BIOS and EFI bootloaders are completely different. The BIOS equivalent of this project is Freeloader, which is part of ReactOS, but it only supports up to XP.

**Comment by ale5000-git** [comment]
@maharmstone: Shouldn't it work up to Windows 7 with your patches?

**Comment by maharmstone** [comment]
If they've been accepted by now, yes!

**Comment by ale5000-git** [comment]
Many changes are already merged, but these 2 are currently missing to boot Windows 7 (if I'm not wrong):
https://github.com/reactos/reactos/pull/1905
https://github.com/reactos/reactos/pull/1958

It shouldn't be difficult for the ones needing it.
