### ISSUE TITLE
x64 binaries in the 20200405 release are broken?

### ISSUE THREAD

**Issue by lideming** [maharmstone/quibble#22]
I can't run `quibble-20200405.zip/amd64/quibble.efi` from x64 EFI shell, but the one in `quibble-20200213.zip` can be run.

And the file size is weird:
* `quibble-20200405.zip/amd64/quibble.efi` (original) size: 144,376 bytes
* `quibble-20200213.zip/amd64/quibble.efi` (original) size: 411,610 bytes

**Comment by RuthgerD** [comment]
Can confirm that the latest release is not working (while the older one does run).

**Comment by maharmstone** [comment]
I'm not altogether sure what happened there - I think I must have messed something up in the packaging process...

I've just recompiled and reuploaded this version: https://github.com/maharmstone/quibble/releases/download/20200405/quibble-20200405.zip. Does this work any better?

**Comment by RuthgerD** [comment]
That makes things bootable again, thanks.
