### ISSUE TITLE
Support for Win 10 2004

### ISSUE THREAD

**Issue by madsl** [maharmstone/quibble#27]
I saw in the source code that 1909 (well, 1903, but since 1909 uses the same values) is the highest supported Win10 version - how do you find these values? I have a ntfs2btrfs-readied partition with Windows 10 2004 to test with, but I'm not sure how boot.c should look for it to find windows 10...

Great work, by the way!

**Comment by maharmstone** [comment]
Thanks. Just as you would for any other bit of reverse engineering - by snooping on what the original does.

IIRC there's no change between 1909 and 2004.

**Comment by madsl** [comment]
Ah.. maybe the issue is the machine I test with does not have a complete CSM module or something. I don't even get a menu showing when I start up quibble.efi, neither directly from bios nor from an uefi shell.

Is the btrfs(uuid) syntax in SystemPath referring to PARTUUID or the fs UUID?

**Comment by madsl** [comment]
It just hit me - I guess if you want to test this on hardware, you should install Windows through legacy boot/CSM for Quibble to be able to boot it? I guess I'll try that, for fun :P

**Comment by maharmstone** [comment]
I could have sworn there was no difference between 1909 and 2004, but I had to add code for 2004 in the latest release. Maybe Microsoft made a change after release, or maybe I'm just losing it.

Either way, the latest version supports 2004 and 2009.

**Comment by TheMadHau5** [comment]
> Is the btrfs(uuid) syntax in SystemPath referring to PARTUUID or the fs UUID?

The fs uuid (see issue 28).
