### ISSUE TITLE
EFI timers not suppoted on Broadwell HP ProBooks

### ISSUE THREAD

**Issue by nikp123** [maharmstone/quibble#28]
I tried to boot Quibble from efi shell, but the timer events seem to be unsupported on my BIOS-es EFI build.

Possible workaround: Disable the timer alltogether in freeldr.ini

![JPEG_20201014_134921_8539949988123171445](https://user-images.githubusercontent.com/4696350/95984863-1e9ab900-0e24-11eb-970b-82ff9f3e375e.jpg)

**Comment by nikp123** [comment]
There is an option, I just missed it. Sorry for the inconvenience

**Comment by maharmstone** [comment]
You mean there's an option in Quibble, or an option in your EFI settings to enable timers?

**Comment by nikp123** [comment]
> You mean there's an option in Quibble, or an option in your EFI settings to enable timers?

No, I meant disabling the timeout alltogether (in freeldr.ini) worked.

**Comment by nikp123** [comment]
Also, unrelated, but now I get ARC errors. Do I put the GPT partition UUID or BTRFS partition UUID

**Comment by maharmstone** [comment]
`No, I meant disabling the timeout alltogether (in freeldr.ini) worked.`
Okay, but that's just a workaround - I'm going to reopen this because I need to find out why CreateEvent is failing.

`Do I put the GPT partition UUID or BTRFS partition UUID`
The Btrfs one.

**Comment by nikp123** [comment]
> `Do I put the GPT partition UUID or BTRFS partition UUID`
> The Btrfs one.

Still not working (ARC error)

**Comment by nikp123** [comment]
> > `Do I put the GPT partition UUID or BTRFS partition UUID`
> > The Btrfs one.
> 
> Still not working (ARC error)

Found out why, the btrfs driver refuses to mount due to compression ``incompat_flags 10``.
Just add a warning that compressed volumes dont work yet. Or just tell the user to decompress their drive before proceeding.

**Comment by maharmstone** [comment]
Yes, I still need to finish off the btrfs EFI driver.

I think the CreateEvent problem is probably this bug, fixed in 2008 but apparently not in your firmware: https://git.bsdio.com/bcran/edk2-bhyve/commit/51b02d81f01441e2aadae1d0bcd46560a93e6f12

**Comment by nikp123** [comment]
> Yes, I still need to finish off the btrfs EFI driver.
> 
> I think the CreateEvent problem is probably this bug, fixed in 2008 but apparently not in your firmware: https://git.bsdio.com/bcran/edk2-bhyve/commit/51b02d81f01441e2aadae1d0bcd46560a93e6f12

I'm just curious as to how HP managed to deal with 7 year old (at the time) code on a new machine. Also that's the least of this firmware's issues. EFI vars do not work, like, AT ALL. So any dumb windows update can overwrite my primary bootloader.
Sorry to rant, but I feel like I need to tell you what you're dealing with here. And yes I've updated my BIOS recently.

**Comment by maharmstone** [comment]
I'm not surprised. I've heard that EFI-in-the-wild and the specs have a passing resemblance at best.

**Comment by maharmstone** [comment]
The latest version includes a work around for this CreateEvent bug.
