### ISSUE TITLE
ReactOS support as well?

### ISSUE THREAD

**Issue by jeditobe** [maharmstone/quibble#3]
ReactOS support as well?

**Comment by maharmstone** [comment]
I've not tested it, but given that NT 5.2 is supported it _should_ work (and would be a bug in ReactOS if it doesn't). I don't know if WinBtrfs 1.6 works with ReactOS - last time I checked, they had made some changes to the code to get it to work.

**Comment by Matthew-Bradley** [comment]
It would be interesting to compare with Freeloader, considering the overlap. I think the ReactOS people have ReactOS and windows booting from ext2/4 with their loader.

**Comment by MegaZeroX10** [comment]
One guy is going to fork and integrate it into Freeloader.

**Comment by maharmstone** [comment]
He's welcome to, though the biggest hurdle will be the fact that the inline asm won't work with MSVC. I plan to fix this myself for the next version, so he might want to hang fire until then.

**Comment by learn-more** [comment]
Just ignore this Zero3K alt, he is not speaking for reactos or hbelusca in any way :)

**Comment by adamantinum** [comment]
Hi, 
I tried Quibble to boot ReactOS, sadly it doesn't work. I link the error returned, maybe it could be useful.
![Schermata del 2020-10-14 16-13-02](https://user-images.githubusercontent.com/50221095/96001884-cb7f3100-0e38-11eb-8cb7-dfd44f093906.png)
