### ISSUE TITLE
CPU type gets recognized incorrectly on some linux distros

### ISSUE THREAD

**Issue by nikp123** [maharmstone/quibble#30]
On ArchLinux quibble fails to build due to CMAKE_SYSTEM_PROCESSOR being x86_64 instead of AMD64 (as, I persume, you expected) in CMakeLists.txt.

Please consider fixing this.

**Comment by nikp123** [comment]
A possible workaround is to add:
```
if(${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64")
    set(CMAKE_SYSTEM_PROCESSOR "AMD64")
endif()
```

**Comment by maharmstone** [comment]
Thanks - I've seen this issue in other projects, so I'm not surprised. Should be fixed by https://github.com/maharmstone/quibble/commit/ebc9171041fddadab91456a03cadf1663995ae2e.
