### ISSUE TITLE
Are there any plans to develop quibble that will work under BIOS?

### ISSUE THREAD

**Issue by daiaji** [maharmstone/quibble#31]
I want to use quibble in 16-bit real mode.
And does Quibble now support Squashfs, Aufs /overlayfs, EROFS?

**Comment by maharmstone** [comment]
No - BIOS is a different beast altogether, and would be a completely different project. Freeldr is perhaps what you're looking for.

And as far as I'm aware, there's no Windows driver for any of those filesystems... there's no point in getting a bootloader to work with a FS if the OS itself can't understand it.
