### ISSUE TITLE
computer reboots after loading

### ISSUE THREAD

**Issue by sonicrules1234** [maharmstone/quibble#39]
Since I had problems with ntfs2btrfs, I just copied all the files from my Windows partition to a btrfs subvolume.  I got into quibble, and it had a bunch of lines about loading from different memory addresses, but when it finished, my computer just reboots.

**Comment by maharmstone** [comment]
What's your motherboard?

**Comment by sonicrules1234** [comment]
Gigabyte X570 AORUS PRO WIFI ATX AM4 Motherboard

**Comment by sonicrules1234** [comment]
It gets further than this now, so I'm going to close this and open a new issue for where it gets stuck now.
