### ISSUE TITLE
Support For Windows 10 Insiders (Dev channel - latest version)

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [maharmstone/quibble#41]
Can you add support for Windows 10 Insider OS dev builds

**Comment by maharmstone** [comment]
No, they're not stable. I'd have to test each and every new build to do this, which isn't feasible.

**Comment by admin-elvistrujanovic** [comment]
> No, they're not stable. I'd have to test each and every new build to do this, which isn't feasible.

Can you then tell me which files I need to copy from that same build (or how to bypass version check on bootloader files) to 32 bit Windows (EFI bootloader) to run Windows 10 32 bit via UEFI which only supports 64-bit

**Comment by TheMadHau5** [comment]
It is possible (and should just work) to run 32-bit operating systems on a 64-bit EFI, the other way around is not so simple.

**Comment by admin-elvistrujanovic** [comment]
> It is possible (and should just work) to run 32-bit operating systems on a 64-bit EFI, the other way around is not so simple.

I tried to boot the 32 bit OS via UEFI from USB but simply, UEFI doesn't see it. Since I can't install or convert to UEFI mbrtogpt.exe as I tried once because the bootloader doesn't see it, which files should I copy (bootloader files) from the 64-bit UEFI OS for booting to be possible?
