### ISSUE TITLE
Does quibble work with bcache?

### ISSUE THREAD

**Issue by Tank-Missile** [maharmstone/quibble#45]
I have a bcache partition formatted to btrfs with windows installed to a subvolume on that partition. I'm not exactly sure how I would add quibble.efi to my UEFI boot options. I rather create a GRUB menu entry for it, but there's no documentation on how to do that.

**Comment by maharmstone** [comment]
Probably not - I don't know anything about how bcache works. Let me know if you try it and it does work.
