### ISSUE TITLE
Windows XP RTM does not start under QEMU 5.2.0

### ISSUE THREAD

**Issue by foxlet** [maharmstone/quibble#48]
Windows XP starts and reaches bootvid, but eventually BSODs with `PROCESS1_INITIALIZATION_FAILED`. Both Quibble 20200213 and XP build 2600 (no service packs) are under FAT32 partitions. Under Quibble 20210111, XP does not reach bootvid at all. 

The original installation boots to desktop when using the SeaBIOS CSM directly.

![Screenshot_20210712_015328](https://user-images.githubusercontent.com/1627533/125238236-f5289400-e2b4-11eb-8fce-a5ded85a20b2.png)
![Screenshot_20210712_015412](https://user-images.githubusercontent.com/1627533/125238241-f78aee00-e2b4-11eb-952e-b020ae7e3e94.png)
![Screenshot_20210712_015429](https://user-images.githubusercontent.com/1627533/125238246-f8bc1b00-e2b4-11eb-8c3c-d0e21f07e35a.png)

**Comment by maharmstone** [comment]
Thanks, I'll try to reproduce. It's interesting that it identifies it as NT 5.0, rather than 5.1 - I'm not sure if that's relevant...

**Comment by foxlet** [comment]
Alrighty, thanks for taking a look!

**Comment by maharmstone** [comment]
The problem here was it didn't know that it had to load fastfat.sys if it was booting from FAT - I've added code to deal with that. The latest master works fine with XP on FAT under Qemu 6.

If you don't want to want to recompile, try setting Start in HKLM\SYSTEM\CurrentControlSet\services\fastfat to 0, which should have the same effect.

**Comment by foxlet** [comment]
I can confirm it works, thank you! however I have also noticed a bug where 512MB of RAM works fine, but 1GB of RAM causes an `IRQL_NOT_LESS_OR_EQUAL` bugcheck. I can make a separate post for that.
