### ISSUE TITLE
[INFO] Windows 2000 under QEMU 6.0

### ISSUE THREAD

**Issue by foxlet** [maharmstone/quibble#49]
This is more to document behavior than a bug (as I'd assume this is outside of the project scope) but Windows 2000 (Service Pack 4, build 2195) does not currently boot due to a lack of support of registries using `CM_KEY_FAST_LEAF` for indexes.

![Screenshot_20210717_224757](https://user-images.githubusercontent.com/1627533/126054095-2785fc7a-bc33-4aa3-ab66-f627d272c162.png)

**Comment by maharmstone** [comment]
Thanks. I've not tested against Windows 2000 at all, but it's something I'll look into.

**Comment by maharmstone** [comment]
After playing around with this for a while, I'm reluctantly classifying this as WONTFIX.

Unlike XP and above, Windows 2000 relies on physical addresses being mapped to predictable virtual addresses by the bootloader. And as it also wants to know how many VA pages we've allocated, this implies that physical addresses need to be allocated contiguously - which is something that the EFI specification isn't set up to handle. Sorry.

**Comment by foxlet** [comment]
Bummer, but thanks for taking a look anyway!
