### ISSUE TITLE
error - cutting into non-free mapping (vmware workstation, windows 11, btrfs)

### ISSUE THREAD

**Issue by typecasto** [maharmstone/quibble#55]
![image](https://user-images.githubusercontent.com/9502466/135540410-742d99a1-f922-4583-9a7d-7b4f1c8e2e38.png)

I get that error every time I try to boot quibble.efi.
I'm using windows 11, converted to btrfs with ntfs2btrfs, on a vmware workstation VM. 
I'm specifying the partition (the big one with all the windows files on it) via UUID in freeldr.ini. (same thing happens when I use partition number though)
I've tried the latest release, and also building from source, and I get the same issue.

I've tried using the free efi drivers from efi.akeo.ie, and I get a different error, but still no boot.

**Comment by maharmstone** [comment]
From the README:
> able to boot every version of Windows from XP to Windows 10 2009

I haven't even started to look at Windows 11 yet.

**Comment by thecakeisalie25** [comment]
Ah, my bad. I'll switch back to 10 for the time being.

**Comment by thecakeisalie25** [comment]
On windows 10 it gives me the same issue, but with a third message: 
![image](https://user-images.githubusercontent.com/9502466/135942296-668e113c-92dd-47f1-ad9d-6483153b018b.png)
