### ISSUE TITLE
Would it be possible to run Windows 2000 on UEFI via Quibble?

### ISSUE THREAD

**Issue by 2W10** [maharmstone/quibble#59]
Hello,

Would it be possible to run Windows 2000 on UEFI with Quibble? Based on the FAQs, it says that any earlier versions than XP ought to work, but the BTRFS driver wouldn't work. So in theory, would it technically be possible to install Windows 2000 on UEFI with Quibble? Should I use VMware or some different VM program?

**Comment by maharmstone** [comment]
I have looked at this issue since, just forgot to update the README - I think it'll be somewhere in the closed issues if you have a look. It turns out Windows 2000 requires a correspondence between physical and virtual memory that can't be done easily with EFI, so unfortunately this isn't feasible.
