### ISSUE TITLE
Boot 32bit Windows XP from 64bit UEFI

### ISSUE THREAD

**Issue by GeorgeK1ng** [maharmstone/quibble#60]
Hi, I'm trying to find out, how to boot 32bit XP from 64bit UEFI environment. 
Currently there is no chance how to do it? 

I have project XP2ESD that allow deploying Windows XP in same way as newer Windows from install.wim / install.esd.
I can boot my Windows 8.0 based installer installer under x64 UEFI. Then is created FAT32 boot partition and system one. I can boot into Quibble, but it's not possible to launch system. I have added NTFS driver from [https://efi.akeo.ie/](https://efi.akeo.ie/).

When I'm trying to load Windows XP 32bit - boot process fails 
![image](https://user-images.githubusercontent.com/98261225/151719412-11c6683c-3896-4828-9a0e-7108a0d8d278.png)

When I'm trying to load Windows XP 64bit - it hangs on isapnp.dll. I checked file header and it seems correctly as x64 PE
![image](https://user-images.githubusercontent.com/98261225/151718533-55b04b9a-2c55-4ac5-92f8-899ea1a496e4.png)

I have checked your To-Do list and seems you have these things here. **Booting 32-bit Windows on 64-bit machine** & 
**Add NTFS driver**

Do you have news about these two things? It would be great to have working solution for booting Windows XP under UEFI. 

I can privately share my testing ISO to reproduce Windows XP x64 isapnp.dll error.

**Comment by atmgnd** [comment]
>> When I'm trying to load Windows XP 64bit - it hangs on isapnp.dll. I checked file header and it seems correctly as x64 PE

the grub's ntfs driver may load sparse driver with incorrect data, on 64bit uefi , this driver may help: https://atmgnd.cn/dl/vboot/ntfs.efi

**Comment by atmgnd** [comment]
> > When I'm trying to load Windows XP 64bit - it hangs on isapnp.dll. I checked file header and it seems correctly as x64 PE
> 
> the grub's ntfs driver may load sparse file with incorrect data, on 64bit uefi , this driver may help: https://atmgnd.cn/dl/vboot/ntfs.efi

Also found that grub's ntfs failed to read files with multi data streams

**Comment by atmgnd** [comment]
> Also found that grub's ntfs failed to read files with multi data streams

[ntfs.zip](https://github.com/maharmstone/quibble/files/10799499/ntfs.zip)

I upload a test binary support read multi data streams and sparse file. Use at Your Own Risk

**Comment by maharmstone** [comment]
I'd be surprised if a file loaded during boot is either sparse or has alternate data streams. But nevertheless, I'm fairly certain that the issue here is with the Batard driver.

The next version of Quibble ought to have my own NTFS driver, so you might want to try again then.

**Comment by atmgnd** [comment]
Agreed. It's unlikyly that file loaded at boot phase are sparse file or has ads. just point out that some features may not supported  grub's ntfs driver. And There may be other reasons for this issue
