### ISSUE TITLE
Windows XP x64: EFI_NOT_FOUND

### ISSUE THREAD

**Issue by 2W10** [maharmstone/quibble#89]
Hi,

I am trying to boot Windows XP x64 using Quibble, but I get the error EFI_NOT_FOUND. How can I fix this?
![Windows XP Professional x64 Edition-2023-04-09-11-41-24](https://user-images.githubusercontent.com/80082089/230787402-d0b5d1f4-8f99-4df6-bfec-794978cf6f2a.png)

**Comment by maharmstone** [comment]
For XP you'll need to find a version of the UEFI firmware with CSM support included.

**Comment by 2W10** [comment]
> For XP you'll need to find a version of the UEFI firmware with CSM support included.

Ok. I am using VMWare. Should I use another hypervisor. Also I am thinking of using this to install XP on UEFI-only Surface Pro 1, would this work? If so, would it be possible for CSM to not be required in the future?

**Comment by yurikoles** [comment]
Support for the UEFI-only boot (no CSM) was added in x64 Windows Vista / Server 2008 SP1 (NT 6.0.6001), x64 Windows XP / Server 2003 (NT 5.2.x) doesn't support it.

**Comment by maharmstone** [comment]
@yurikoles - I don't think that's right. IIRC it's Windows 8 that's the first not to need the CSM.

@2W10 - this could be done by reimplementing the relevant BIOS interrupts, but it's not something I'm planning to do at the moment. It'd be quite a big job, and its only use would be allowing very old software to run on very new hardware. Sorry.

**Comment by ruevs** [comment]
> @yurikoles - I don't think that's right. IIRC it's Windows 8 that's the first not to need the CSM.

That is correct. Booting Windows 7 on an UEFI system without a CSM is an awful hack (mostly involving VGA.sys) that may or may not work.

**Comment by 2W10** [comment]
> @yurikoles - I don't think that's right. IIRC it's Windows 8 that's the first not to need the CSM.
> 
> 
> 
> @2W10 - this could be done by reimplementing the relevant BIOS interrupts, but it's not something I'm planning to do at the moment. It'd be quite a big job, and its only use would be allowing very old software to run on very new hardware. Sorry.

Ok I understand. Could it possibly be done in the far future?

**Comment by qwertychouskie** [comment]
Something like https://github.com/CloverHackyColor/CloverBootloader is probably closer to what you are looking for.  Clover is usually used to provide uEFI support on BIOS systems, but from a quick skim of the readme, it sounds like the reverse *may* be possible.

**Comment by 2W10** [comment]
> Something like https://github.com/CloverHackyColor/CloverBootloader is probably closer to what you are looking for.  Clover is usually used to provide uEFI support on BIOS systems, but from a quick skim of the readme, it sounds like the reverse *may* be possible.

Where does it say that? It doesn't sound like that to me.

**Comment by maharmstone** [comment]
> > @yurikoles - I don't think that's right. IIRC it's Windows 8 that's the first not to need the CSM.
> > @2W10 - this could be done by reimplementing the relevant BIOS interrupts, but it's not something I'm planning to do at the moment. It'd be quite a big job, and its only use would be allowing very old software to run on very new hardware. Sorry.
> 
> Ok I understand. Could it possibly be done in the far future?

I've added it to the to-do list in the README. It looks like the Steam Deck is another machine which comes without a CSM, so it'd be nice to be able to use Windows 7 etc. on that.

**Comment by 2W10** [comment]
> > > @yurikoles - I don't think that's right. IIRC it's Windows 8 that's the first not to need the CSM.
> > > @2W10 - this could be done by reimplementing the relevant BIOS interrupts, but it's not something I'm planning to do at the moment. It'd be quite a big job, and its only use would be allowing very old software to run on very new hardware. Sorry.
> > 
> > 
> > Ok I understand. Could it possibly be done in the far future?
> 
> I've added it to the to-do list in the README. It looks like the Steam Deck is another machine which comes without a CSM, so it'd be nice to be able to use Windows 7 etc. on that.

Yes. It is possible to do something like that. FlashBootPro EFI files emulate the BIOS environment, which is what allowed Vista and 7 to boot on the Surface Pro 1.
