### ISSUE TITLE
ReactOS support

### ISSUE THREAD

**Issue by erkinalp** [maharmstone/quibble#90]
ReactOS is a free open source reimplementation of Windows XP/2003.

**Comment by maharmstone** [comment]
ReactOS' aim is to be exactly compatible with Windows XP, so if Quibble works with XP but not ReactOS you need to log it as a bug with them.

**Comment by erkinalp** [comment]
@maharmstone ReactOS has its own implementation of NTLDR/BOOTMGR called FreeLdr, which provides an opportunity to integrate the two together to make Quibble the primary bootloader of ReactOS.

**Comment by maharmstone** [comment]
And if they want to do that, they're welcome to. I'm not going to, though.

**Comment by DCFUKSURMOM** [comment]
react os is already working on uefi support
