### ISSUE TITLE
EFI_VOLUME_CORRUPTED when attempting to boot Windows 11 Superlite SE

### ISSUE THREAD

**Issue by halian** [maharmstone/quibble#91]
When attempting to use Quibble 20230328 to boot Ghost Spectre's Superlite SE distro of Windows 11, I get the following error (transcribed from a phone photo):

```
Loaded ntoskrnl.exe at fffff80800000000.
Booting NT version 10.0.22621.1413.
File->Read returned EFI_VOLUME_CORRUPTED
OpenHive returned EFI_VOLUME_CORRUPTED
load_registry returned EFI_VOLUME_CORRUPTED
boot returned EFI_VOLUME_CORRUPTED
```

**Comment by maharmstone** [comment]
I don't know where you've got "not planned" from. Windows 11 support isn't yet implemented, but it's very much planned.

**Comment by halian** [comment]
The cause was an imperfect btrfs conversion, so I didn’t want to burden you with what is ultimately a PEBKAC issue. >_<;
