### ISSUE TITLE
Booting process stuck on "Loaded pcw.sys" for Windows 11 22H2

### ISSUE THREAD

**Issue by shanoaice** [maharmstone/quibble#92]
![图片](https://user-images.githubusercontent.com/25174488/234288549-f5130d1b-edc7-4adc-8575-0eb0ef7d960d.png)

## System Information
```
Edition		Windows 11 Home Edition
Version		22H2
OS Version	22621.1631
Experience	Windows Feature Experience Pack 1000.22641.1000.0
```

The README page states that Quibble supports Windows 10 22H2, but I am not sure whether Windows 11 22H2 is supported. Also, I have enabled OS Compression to save disk space, I suspect this could be the source of the problem?

**Comment by yurikoles** [comment]
As you may see, the project readme was updated two weeks ago, so it's being maintained. But Window 11 was released mostly two years ago. Do you consider it wasn't tested or wasn't reported before? Just browse or search in prior issues.

**Comment by maharmstone** [comment]
@shanoaice - no, Windows 11 isn't supported yet. I'll update the README when it is.
